### ISSUE TITLE
stop command not working on try 1

### ISSUE THREAD

**Issue by DatOneLefty** [WHCO/FOS#12]
when i use the stop command, it just logs stop. It doesnt ask y/n and if i enter y, nothing happens. The second time I enter it, it works

**Comment by liam4** [comment]
Hmm.. it works for me:

```
[1]/fos/api/cl $ stop
Program wants to trun off ForceOS!
Do so?
(yes)
(program stops)
```

**Comment by liam4** [comment]
'Kay, it looks it's working now.

First, please do not use `time.sleep` without specifically making it clear to the user that you will be using `time.sleep`. That confuses the user, perhaps making the user think a performance error has occurred.

Second, you had the following code inside of `stop.py`:

```python
foslogging.info("The system is stopping NOW!")
time.sleep (2)
foslogging.stop
```

This was in the top layer of the file, e.g. when imported the code would run. You should _never, ever_ run code on importing, besides declaring functions, constants, classes, etc. This makes bugs hard to track.

In any case, the bug is fixed now! :P

**Comment by DatOneLefty** [comment]
well, i am added scripts to imported items because so i can find bugs in the new recovery mode...
